### ISSUE TITLE
Tests 🧪

### ISSUE THREAD

**Issue by teenie-quaggard** [FACxBeamery/tech-test-tom#5]
I don't see any tests Tom!
Would be lovely to see at least a few in the frontend and backend.

**Comment by thomas-galligan** [comment]
Thanks, tests are my priority today! I have one test on the back-end (in `server/handlers/getJobs.test.js` checking that my cleaning function for the external API response is working, and since you wrote this issue I've added some integration testing on the front end.

**Comment by thomas-galligan** [comment]
I now have some more tests on my back-end, and an extra integration test :)
